name: automatic syntax check

on:
  pull_request:
    branches:
      - master

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.3.0
      - uses: actions/checkout@v2
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --recursive --diff --exit-code --max-line-length=300 .
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          .github_scripts/slack_and_fail.sh
#        env:
#          PIPELINE_PR_FAIL_NOTIFICATION_WH: ${{secrets.PIPELINE_PR_FAIL_NOTIFICATION_WH}}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
         python-version: 3.7
      - name: Install Dependencies
        run: |
          sudo apt-get install python3-pip
          pip3 install --upgrade pip
          pip3 install -r ./test_requirements.txt
      - name: pytest
        run: |
          cd composer
          pytest || ../.github_scripts/slack_and_fail.sh
#        env:
#          PIPELINE_PR_FAIL_NOTIFICATION_WH: ${{secrets.PIPELINE_PR_FAIL_NOTIFICATION_WH}}
