name: automatic syntax check

on:
  pull_request:
    branches:
      - master

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.3.0
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
         python-version: 3.7
      - name: Install Dependencies
        run: |
          sudo apt-get install python3-pip
          pip3 install --upgrade pip
          pip3 install -r ./test_requirements.txt
      - name: pytest
        run: |
          pytest || .github_scripts/slack_and_fail.sh
#        env:
#          PIPELINE_PR_FAIL_NOTIFICATION_WH: ${{secrets.PIPELINE_PR_FAIL_NOTIFICATION_WH}}
